package constants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public interface Constants {

    String FIND_ALL_CUSTOMER = "SELECT * FROM CUSTOMER";
    String FIND_ALL_ORDERS = "SELECT * FROM ORDERS";
    String FIND_ALL_TELECAST = "SELECT * FROM TELECAST";
    String FIND_ALL_TRAILER = "SELECT * FROM TRAILER";
    String FIND_TELECAST_BY_COST_QUERY = "SELECT NAME, RATE FROM TELECAST WHERE COST_MINUTE < ?";
    String FIND_TELECAST_BY_TRAILER_QUERY = "SELECT TELECAST.NAME, RELEASE_DATE FROM TELECAST " +
            "JOIN ORDERS ON REF_TELECAST = ID_TELECAST " +
            "JOIN TRAILER ON ID_TRAILER = REF_TRAILER " +
            "WHERE TRAILER.NAME = ?; ";

    String TELECAST_FIND_ID_BY_NAME = "SELECT ID_TELECAST FROM TELECAST WHERE NAME = ?";
    String CUSTOMER_FIND_ID_BY_NAME = "SELECT ID_CUSTOMER FROM CUSTOMER WHERE FIRM = ?";
    String TRAILER_FIND_ID_BY_NAME = "SELECT ID_TRAILER FROM TRAILER WHERE NAME = ?";

    String FIND_TRANSLATION_COST_BY_NAME_QUERY = "SELECT (TELECAST.NAME) AS NAME, (EXTRACT (MINUTE FROM DURATION) * " +
            "COST_MINUTE + EXTRACT (SECOND FROM DURATION) * COST_MINUTE / 60) " +
            "AS TRANSLATION_COST FROM TELECAST " +
            "JOIN ORDERS ON REF_TELECAST = ID_TELECAST " +
            "JOIN TRAILER ON REF_TRAILER  = ID_TRAILER " +
            "WHERE TELECAST.NAME = ?";
    String FIND_AMOUNT_TELECASTS_UPON_RATE_QUERY = "SELECT (COUNT(NAME)) AS AMOUNT_TELECASTS FROM TELECAST " +
            "WHERE RATE > ?";
    String FIND_TELECASTS_AND_TRAILER_BY_RELEASE_DARE_QUERY = "SELECT (TELECAST.NAME) AS TELECAST, (TRAILER.NAME) AS " +
            "TRAILER FROM TELECAST " +
            "JOIN ORDERS ON REF_TELECAST = ID_TELECAST " +
            "JOIN TRAILER ON REF_TRAILER = ID_TRAILER " +
            "WHERE RELEASE_DATE = ?";

    String FIND_ALL_RELEASE_DATE_QUERY = "SELECT RELEASE_DATE FROM ORDERS";

    String INSERT_NAME_DURATION_QUERY = "MERGE INTO TRAILER (NAME, DURATION ) KEY (NAME, DURATION ) VALUES (?, ?)";
    String MERGE_INTO_ORDERS_QUERY = "MERGE INTO ORDERS (REF_CUSTOMER, REF_TELECAST, REF_TRAILER, RELEASE_DATE) " +
            "KEY (RELEASE_DATE) VALUES ( " +
            "(SELECT ID_CUSTOMER FROM CUSTOMER WHERE FIRM = 'P&G'), " +
            "(SELECT ID_TELECAST FROM TELECAST WHERE NAME = ?), " +
            "(SELECT ID_TRAILER FROM TRAILER WHERE NAME = ?), " +
            "?) ";

    String INSERT_INTO_ORDERS_QUERY = "INSERT INTO ORDERS (REF_CUSTOMER, REF_TELECAST, REF_TRAILER, RELEASE_DATE) " +
            "VALUES (?, ?, ?, ?)";
    String UPDATE_COST_PER_MINUTE_QUERY = "UPDATE TELECAST SET COST_MINUTE = ? * COST_MINUTE WHERE NAME = ?";
    List<String> DELETE_TRAILER_QUERY = Arrays.asList("DELETE FROM ORDERS WHERE REF_TRAILER = (SELECT ID_TRAILER " +
            "FROM TRAILER WHERE NAME = ?)", "DELETE FROM TRAILER WHERE NAME = ?");


    String TELECAST_NAME_COLUMN_NAME = "NAME";
    String TELECAST_ID_COLUMN_NAME = "ID_TELECAST";
    String TELECAST_RATE_COLUMN_NAME = "RATE";
    String TELECAST_COST_PER_MINUTE_COLUMN_NAME = "COST_MINUTE";
    String AMOUNT_TELECASTS_COLUMN_NAME = "AMOUNT_TELECASTS";
    String TELECAST_COLUMN_NAME = "TELECAST";


    String ID_CUSTOMER_COLUMN_NAME = "ID_CUSTOMER";
    String CUSTOMER_FIRM_COLUMN_NAME = "FIRM";
    String CUSTOMER_CONTACT_PERSON_COLUMN_NAME = "CONTACT_PERSON";
    String CUSTOMER_TELEPHONE_COLUMN_NAME = "TELEPHONE";
    String CUSTOMER_CODE_COLUMN_NAME = "CODE";

    String ORDERS_REF_CUSTOMER_COLUMN_NAME = "REF_CUSTOMER";
    String ORDERS_REF_TELECAST_COLUMN_NAME = "REF_TELECAST";
    String ORDERS_REF_TRAILER_COLUMN_NAME = "REF_TRAILER";
    String ORDERS_RELEASE_DATE_COLUMN_NAME = "RELEASE_DATE";

    String TRAILER_COLUMN_NAME = "TRAILER";
    String ID_TRAILER_COLUMN_NAME = "ID_TRAILER";
    String TRAILER_NAME_COLUMN_NAME = "NAME";
    String TRAILER_DURATION_COLUMN_NAME = "DURATION";

    String TRANSLATION_COST_COLUMN_NAME = "TRANSLATION_COST";

    String INSERT_TRAILER_QUERY = "INSERT INTO TRAILER (ID_TRAILER, NAME, DURATION ) VALUES (?, ?, ?)";

    String FIND_DATA_BY_TABLE_NAME = "SELECT * FROM ";
}
